### ISSUE TITLE
Bug: playwright sync cannot read innerHtml of page when running alongside jupyter notebook

### ISSUE THREAD

**Issue by slimykat** [FHPythonUtils/SvgTrace#2]
## Question

- [ x] I have read the comment above and have completed each step

**steps:**
I open python on my terminal for testing, while jupyter notebook is running in the background.
Package importing was successful, but the function call failed after running for a few seconds.
An empty SVG file was created.

As mentioned in the title, I suspect this situation has something to do with my environment. 

**environment:**
macOS Catalina 10.15.7
python3.9 (Homebrew)

**Traceback:**
```console
>>>Path("outPath.svg").write_text(trace("inPath.png", True), encoding="utf-8")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/svgtrace/__init__.py", line 50, in trace
    svg = page.evaluate("(element) => element.innerHTML", element)
  File "/usr/local/lib/python3.9/site-packages/playwright/sync_api/_generated.py", line 8611, in evaluate
    self._sync(
  File "/usr/local/lib/python3.9/site-packages/playwright/_impl/_sync_base.py", line 104, in _sync
    return task.result()
  File "/usr/local/lib/python3.9/site-packages/playwright/_impl/_page.py", line 410, in evaluate
    return await self._main_frame.evaluate(expression, arg)
  File "/usr/local/lib/python3.9/site-packages/playwright/_impl/_frame.py", line 277, in evaluate
    await self._channel.send(
  File "/usr/local/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 44, in send
    return await self._connection.wrap_api_call(
  File "/usr/local/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 419, in wrap_api_call
    return await cb()
  File "/usr/local/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 79, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: TypeError: Cannot read properties of null (reading 'innerHTML')
    at eval (eval at evaluate (:197:30), <anonymous>:1:22)
    at UtilityScript.evaluate (<anonymous>:204:19)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
>>> 
```

**Comment by FredHappyface** [comment]
Hey tried this out and seems to happen if the source file doesn't exist. That is a bug and is fixed in 2023.0.1. Would you be able to confirm this when you get the chance?

Thank you :)

**Comment by slimykat** [comment]
@FredHappyface  Thanks for the reply. Unfortunately the 2023.0.1. release seems the same to me.

**Comment by slimykat** [comment]
Here's what I tried
```console
 % git checkout tags/2023.0.1
HEAD is now at 39c1165 release 2023.0.1
 %python3
Python 3.9.9 (main, Nov 21 2021, 03:22:47) 
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from svgtrace import trace
>>> source=trace("../img.png")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/liangzhenning/Desktop/test_f/SvgTrace/svgtrace/__init__.py", line 53, in trace
    svg = page.evaluate("(element) => element.innerHTML", element)
  File "/usr/local/lib/python3.9/site-packages/playwright/sync_api/_generated.py", line 8611, in evaluate
    self._sync(
  File "/usr/local/lib/python3.9/site-packages/playwright/_impl/_sync_base.py", line 104, in _sync
    return task.result()
  File "/usr/local/lib/python3.9/site-packages/playwright/_impl/_page.py", line 410, in evaluate
    return await self._main_frame.evaluate(expression, arg)
  File "/usr/local/lib/python3.9/site-packages/playwright/_impl/_frame.py", line 277, in evaluate
    await self._channel.send(
  File "/usr/local/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 44, in send
    return await self._connection.wrap_api_call(
  File "/usr/local/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 419, in wrap_api_call
    return await cb()
  File "/usr/local/lib/python3.9/site-packages/playwright/_impl/_connection.py", line 79, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: TypeError: Cannot read properties of null (reading 'innerHTML')
    at eval (eval at evaluate (:197:30), <anonymous>:1:22)
    at UtilityScript.evaluate (<anonymous>:204:19)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
>>> import os
>>> os.path.isfile(f"../img.png")
True

**Comment by slimykat** [comment]
also I've tried importing using SvgTrace.svgtrace, the result was the same.

**Comment by FredHappyface** [comment]
Hmm honestly not too sure, though admittedly I do not use jupyter notebooks. Does this happen when it is not running in the background out of curiosity?

Looks like this is a known issue with playwright and is linked to #3 

https://stackoverflow.com/a/71702599

**Comment by FredHappyface** [comment]
Fixed in https://github.com/FHPythonUtils/SvgTrace/releases/tag/2023.1 

Note using svgtrace.trace/ asyncTrace raises an OSError as it is not supported in Windows Jupyter Notebooks. (https://github.com/jupyter/notebook/issues/5916)


However, you can use `skimageTrace` for basic conversion (based on edge detection)

```python
def skimageTrace(image: Image.Image) -> str:
```
